-- GroupBuy 저장과 Redis 판정 예약 사이의 유실을 막기 위한 Transactional Outbox
CREATE TABLE "outbox_event" (
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "event_type"      VARCHAR(50) NOT NULL,
    "aggregate_id"    BIGINT NOT NULL,
    "scheduled_at"    TIMESTAMP NOT NULL,
    "status"          VARCHAR(20) NOT NULL,
    "retry_count"     INT NOT NULL DEFAULT 0,
    "next_attempt_at" TIMESTAMP NOT NULL,
    "published_at"    TIMESTAMP NULL,
    "created_at"      TIMESTAMP NOT NULL DEFAULT now(),
    "updated_at"      TIMESTAMP NULL,
    CONSTRAINT "pk_outbox_event" PRIMARY KEY ("id"),
    CONSTRAINT "uq_outbox_event_type_aggregate_id"
        UNIQUE ("event_type", "aggregate_id"),
    CONSTRAINT "ck_outbox_event_status"
        CHECK ("status" IN ('PENDING', 'PUBLISHED')),
    CONSTRAINT "ck_outbox_event_type"
        CHECK ("event_type" IN ('GROUP_BUY_JUDGMENT_SCHEDULED'))
);

-- 발행 완료 이벤트를 제외하고 현재 재시도 가능한 이벤트만 빠르게 조회한다.
CREATE INDEX "idx_outbox_event_publishable"
    ON "outbox_event" ("next_attempt_at", "id")
    WHERE "status" = 'PENDING';
