/* ============================================================================
 * orders.id 를 IDENTITY 에서 standalone SEQUENCE 로 전환
 *
 * 배경: V1 에서 GENERATED BY DEFAULT AS IDENTITY 로 생성된 orders_id_seq 는
 *       PostgreSQL internal identity sequence 로, Hibernate 6 의 스키마
 *       검증(ddl-auto: validate)이 information_schema.sequences 에서 탐지하지
 *       못해 missing sequence 오류 발생.
 *       V9 의 ALTER SEQUENCE 는 identity sequence 에 적용됐으나 근본 문제
 *       해결이 안 된 상태였음.
 *       ProductAwardEvaluation(V13) 과 동일한 방식으로 standalone sequence
 *       로 전환하여 Hibernate 6 validator 가 정상 탐지하도록 수정.
 * ==========================================================================*/

-- IDENTITY 제거 (소유 중인 identity sequence 도 함께 삭제됨)
ALTER TABLE orders
    ALTER COLUMN id DROP IDENTITY IF EXISTS;

-- standalone sequence 생성 (allocationSize = 20 에 맞춰 INCREMENT BY 20)
CREATE SEQUENCE IF NOT EXISTS orders_id_seq INCREMENT BY 20;

SELECT setval(
    'orders_id_seq',
    COALESCE((SELECT MAX(id) FROM orders), 1)
);

ALTER TABLE orders
    ALTER COLUMN id SET DEFAULT nextval('orders_id_seq');

ALTER SEQUENCE orders_id_seq OWNED BY orders.id;
